services:
  khaos:
    build: .
    container_name: khaos
    networks:
      - khaos
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: khaos-postgres
    networks:
      - khaos
    env_file:
      - .env
    volumes:
      - ./dev-persist/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432 # allows psql / localhost diesel to connect easily
networks:
  khaos:
    external: false
